name: task_checker
description: Task status checker project.
version: 1.0.2


# Add this section to specify the Dart SDK version constraint.
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6

  # Add other dependencies if you have any.
  # Example:
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
